### PR TITLE
Update for ecto_sql 3.6.0

### PR DESCRIPTION
**Pull request by warmwaffles**
I am not at a machine right now to cut a release, but I was running into issues with ecto in a project I had with `lock_for_migrations/4`

### CODE REVIEW

**Comment by warmwaffles** [comment]
Also  should we change the mix dep to use `>=` instead of `~>` for `ecto_sql`?

Change to 

```
{:ecto_sql, ">= 3.6.0"}
```

**Comment by warmwaffles** [comment]
Have some SQL query generation errors.

**Comment by warmwaffles** [comment]
Simplified SQL that is failing

```sql
INSERT INTO posts (title) (SELECT concat(p0.title, CAST(? AS TEXT), p0.id) FROM posts AS p0);
```

**Comment by warmwaffles** [comment]
More info

```
sqlite> INSERT INTO posts (title) VALUES (SELECT concat(p0.title, CAST(? AS TEXT), p0.id) FROM posts AS p0);
Error: near "SELECT": syntax error
sqlite> INSERT INTO posts (title) (SELECT concat(p0.title, CAST(? AS TEXT), p0.id) FROM posts AS p0);
Error: near "(": syntax error
sqlite> INSERT INTO posts (title) SELECT concat(p0.title, CAST(? AS TEXT), p0.id) FROM posts AS p0;
Error: no such function: concat
sqlite> INSERT INTO posts (title) SELECT 'foo' FROM posts AS p0;
sqlite> INSERT INTO posts (title) (SELECT 'foo' FROM posts AS p0);
Error: near "(": syntax error
```

So we can not wrap the `SELECT` in params to insert.

**Comment by warmwaffles** [comment]
They added `concat` to the upstream `ecto` integration tests. SQLite does not support that function, but can be accomplished with `'str' || 'foo'`

**Comment by warmwaffles** [comment]
Documentation for SQLite says to at least provide a `where true` if we are going to use an `on conflict` to avoid ambiguity.

**Comment by warmwaffles** [comment]
I've got a PR open to tag the integration tests.

**Comment by warmwaffles** [comment]
@kevinlang ball is in ecto's court now. In order to get this and move forward with out a release from ecto we'll need to copy the repo test entirely and change the tests.

Not a huge fan of pulling the tests from the dependency since we have to wait for upstream to merge and then release.

**Comment by kevinlang** [comment]
> Not a huge fan of pulling the tests from the dependency since we have to wait for upstream to merge and then release.

Yeah, it is not ideal. However, none of the alternatives are great either.

1. Pull in `ecto` and `ecto_sql` from `git` directly via mix. But this results in the test environment being different than the actual usage/prod environment, more or less. 
2. Only load in the test files via `git` for `ecto` and `ecto_sql`, but keep using the published versions in dev/test/prod envs. However, if either of those repositories add a new feature and add tests for that new feature in the integration tests (as they should), then we will be broken as we are using the published dependency against the integration `exs` script files in `master`.
3. Fork the tests entirely. This ends up being more work than our current approach, and makes us less likely to get test improvements from upstream.

**Comment by kevinlang** [comment]
I forked the `repo.exs` tests over and added a new `:placeholders` exclusion that I haven't looked into (we may be able to actually support it instead of excluding, don't know).

I also un-forked all the other tests, and bumped min `ecto_sql` to 3.6, since the callback we implement has changed.

**Review by kevinlang — APPROVED** [review]

**Comment by kevinlang** [comment]
Split out the parameters thing to #22 , as it looks like it _may_ require exqlite changes, first.

Merging this, feel free to cut a release if desired, @warmwaffles

**Comment by warmwaffles** [comment]
Thanks I appreciate it. I got back to my main dev workstation.

**Pull request merged**
