### PR TITLE
Add mix_test_watch v1.1.0 as dev dep

### PR DESCRIPTION
**Pull request by joeljuca**
Hello!

Please consider this PR as a suggestion to add `mix_test_watch` as a dev dependency. It's good to have a lightweight test watcher running while you work on something in the library. :)

### CODE REVIEW

**Comment by joeljuca** [comment]
I'm not totally sure if it would include `mix_test_watch` in the releases, though. I hope not – but I saw other dev/test-only projects like `benchee`, `ex_doc`, `jason`, etc., so I thought it wouldn't affect releases.

**Comment by warmwaffles** [comment]
I'm not a fan of `mix_test_watch` I can accomplish the same thing with https://github.com/eradman/entr. I also don't think this project has enough of active development to find it useful.

**Comment by joeljuca** [comment]
Sounds fair. I also heard about Ruby's `rerun` yesterday, which apparently works similarly to `entr`.

**Comment by warmwaffles** [comment]
`entr` is pretty sweet, I use it for other projects and it works well 99% of the time.

**Pull request closed without merging**
