### PR TITLE
Update :utc_datetime handling

### LINKED ISSUE #46: :utc_datetime handling
I'm currently in the process of migrating an sqlite_ecto2 project to this adapter and I noticed that this one does seem to store utc_datetime as iso strings with tz information (with trailing `Z`), while `sqlite_ecto2` doesn't store an offset.

The comment here seems to suggest this is not yet set in stone: 
https://github.com/elixir-sqlite/ecto_sqlite3/blob/886bd6f0c27a5b750c356f26c6dce0af28d15f69/lib/ecto/adapters/sqlite3/codec.ex#L49-L54

I'd argue that the adapter doesn't want to push timezone knowledge into the db, just like the other ecto adapters do. Neither postgres nor mysql natively support a datetime column, which does retain timezone information. Even though `timestamptz` for postgres does convert between session timezone and the column value automatically, it also just stores UTC and not the input timezone – and ecto defaults to `timestamp` columns on postgres anyways. Additionally the `:utc_datetime` ecto type already makes sure the datetime is using UTC as timezone at runtime, so other timezones are not allowed for such columns in the first place.

Would you be open to adjusting the handling for `:utc_datetime`?

### PR DESCRIPTION
**Pull request by LostKobrakai**
This changes the handling of `:utc_datetime` to not write offsets to the db and ignore them when fetching.

I'm wondering if this one should be changed as well though. 
https://github.com/elixir-sqlite/exqlite/blob/a173dc87e6094a7beb535773b989d596461a3a75/lib/exqlite/sqlite3.ex#L170

It seems neither postgrex nor myxql support `%DateTime{}`s not being supplied in UTC:
Postgrex: 
https://github.com/elixir-ecto/postgrex/blob/60abc91d7d64155e9d5fe587178e063b1083f668/lib/postgrex/extensions/timestamptz.ex#L52-L54
MyXQL: 
https://github.com/elixir-ecto/myxql/blob/fdb147dba07d7699c4af23448996ae7f4663bce6/lib/myxql/protocol/values.ex#L341-L343

The mssql/tds driver seems to have a type for datetimes with offsets.
https://github.com/livehelpnow/tds/blob/36f228275c2bfde2baa45fe70d29d1eb1d44379b/lib/tds/types.ex#L1775-L1788
Usable with custom ecto types it seems: https://github.com/livehelpnow/tds/pull/111#issuecomment-675193597

This PR will currently ignore any offsets, given there's no clear path on how to handle the offset if there is one.

Closes #46

### CODE REVIEW

**Comment by warmwaffles** [comment]
> I'm wondering if this one should be changed as well though.
> https://github.com/elixir-sqlite/exqlite/blob/a173dc87e6094a7beb535773b989d596461a3a75/lib/exqlite/sqlite3.ex#L170

Yes we should probably alter that there as well.

> This PR will currently ignore any offsets, given there's no clear path on how to handle the offset if there is one.

In theory SQLite3 _should_ shift the offsets upon writing the record to UTC. Not 100% certain on that, but I swear I remember reading it in the sqlite documentation.

**Comment by LostKobrakai** [comment]
Maybe here:

> Formats 2 through 10 may be optionally followed by a timezone indicator of the form "[+-]HH:MM" or just "Z". The date and time functions use UTC or "zulu" time internally, and so the "Z" suffix is a no-op. Any non-zero "HH:MM" suffix is subtracted from the indicated date and time in order to compute zulu time. For example, all of the following time values are equivalent: 

https://www.sqlite.org/lang_datefunc.html

**Comment by warmwaffles** [comment]
Yea that's where I saw it. 👍🏻

**Comment by warmwaffles** [comment]
@LostKobrakai if you can, will you go update the `exqlite` handling of datetimes?

**Comment by LostKobrakai** [comment]
I can do that, I'm just not sure if I should go with an Exception for non UTC datetimes like the other adapters, or an error tuple like everything else seems to be.

**Comment by warmwaffles** [comment]
I modeled both this adapter and the client library to be close to how MyXQL handles things. If either postgrex or myxql raise an exception for that, let's do that to keep parity.

**Pull request merged**
